"""ajuste_post_inicial

Revision ID: 33827e5c8222
Revises: 0001_inicial
Create Date: 2026-07-21 08:03:28.826474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33827e5c8222'
down_revision: Union[str, None] = '0001_inicial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_periodo_por_declarante_anio', 'periodo_gravable', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_periodo_por_declarante_anio', 'periodo_gravable', ['declarante_id', 'anio'])
    # ### end Alembic commands ###
